version: "3.3"

services:
    database:
        restart: always
        container_name: postgres-finance-transaction
        image: postgres
        volumes:
            - ./database/data:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=finance-transaction
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_PORT=5432
        ports:
            - "5442:5432"
